### ISSUE TITLE
Only amount from primary receiver is displayed in PayPal screen

### ISSUE THREAD

**Issue by sarjey** [paypal/adaptivepayments-sdk-dotnet#14]
Version 2.12.117

Consider the following code fragment:

````
receiverList.receiver = new List<Receiver>();
Receiver secondaryReceiver = new Receiver(totalAmount - amount);
secondaryReceiver.email = ConfigurationManager.AppSettings["PORTAL_PAYPAL_EMAIL"];
receiverList.receiver.Add(secondaryReceiver);     

Receiver primaryReceiver = new Receiver(amount);
primaryReceiver.email = primaryEmail; 
primaryReceiver.primary = true; 
receiverList.receiver.Add(primaryReceiver);
````

A dump of `receiverList.ToNVPString("receiverList.")` immediately after this fragment shows:

"receiverList.receiver(0).amount=10.9&receiverList.receiver(0).email=secondary%40androide.no&receiverList.receiver(1).amount=100&receiverList.receiver(1).email=primary%40androide.no&receiverList.receiver(1).primary=true&"

The resulting amount payable in PayPal screen is USD 100. Expected value: 110.90

This was working as expected in an earlier version.

**Comment by jziaja** [comment]
No evidence in the code was found to support this being a bug with the SDK, though I may have originally misunderstood the question.  This might be an account issue, or perhaps the sandbox service wasn't processing the payment correctly.  If you are still experiencing this problem where the payment totals on your PayPal account doesn't match what is expected, please contact [PayPal Merchant Technical Support](https://ppmts.custhelp.com) and they should be able to help you out.
