### ISSUE TITLE
How to get Buyer/Payer Name using Adaptive Payment

### ISSUE THREAD

**Issue by HoneyShyam** [paypal/adaptivepayments-sdk-dotnet#17]
Hi Dear,
Is there any way/method to get Buyer when do a Chained Payment using Adaptive Payment.
Any help will be great.
Thanks in advance.
Regards
Shyam

**Comment by jziaja** [comment]
Hi @HoneyShyam, you have a couple ways of getting the sender name. If the sender has a name attached to their shipping address, you can use the `GetShippingAddresses` call with the paykey and see if you can get their name from that information.  Another option is to use the [Permissions API](https://github.com/paypal/permissions-sdk-dotnet) and `GetBasicPersonalData` using the sender's account ID (which can be obtained with the Adaptive Payments API's `PaymentDetails` call).

**Comment by HoneyShyam** [comment]
Thanks @jziaja, I am using Adaptive Payments API's and getting response on IPN page in rest format.
How can I use PaymentDetails on IPN Page?
Please share some part of code using C#.
Regards
Shyam

**Comment by jziaja** [comment]
Can you clarify what you mean by "rest format"?  The IPN should be received with its content type as "application/x-www-form-urlencoded" and a body containing name-value pairs storing the payment information.

**Comment by HoneyShyam** [comment]
@jziaja it is like 
transaction[1].amount=USD 0.07
reverse_all_parallel_payments_on_error=true
tracking_id=INV-45E133FC
transaction[1].pending_reason=NONE
pay_key=AP-5M3122435M543453R
transaction[1].id=79X63742MV9276110
transaction[0].pending_reason=NONE
transaction[1].invoiceId=INV-45E133FC-M
status=COMPLETED
transaction[1].status=Completed
is a part of response get on IPN Page, and it does not have Buyer first_name or last_name.
Regards
Shyam

**Comment by jziaja** [comment]
From the IPN response, use the `pay_key` and the `transaction[1].id` and make a call to  `PaymentDetails()` with the Adaptive Payments API.  This will get you more information about the payment, including the `sender` information that you can then use to call [`GetBasicPersonalData()`  with the Permissions API](https://developer.paypal.com/docs/classic/api/permissions/GetBasicPersonalData_API_Operation/).  When making that call, you'll need to specify the first and last name attributes in the `attributeList` parameter.

**Comment by HoneyShyam** [comment]
To call GetBasicPersonalData() with the Permissions API, I think we need permission from seller to make the call, I am processing the payment like a merchant.
So can you please provide some sample code. How can I make this call without any prior permission
Regards
Shyam

**Comment by jziaja** [comment]
Yes, you are correct that you'll need that extra permission.  Without that, you're limited to the information you can glean from the [`GetShippingAddresses()`](https://developer.paypal.com/docs/classic/api/adaptive-payments/GetShippingAddresses_API_Operation/) call (where you'll use the `payKey` you got from the IPN).  `selectedAddress.addresseeName` should get you their name from the response object.

The sample project [has an example](https://github.com/paypal/adaptivepayments-sdk-dotnet/blob/master/Samples/AdaptivePaymentsSampleApp/AdaptivePaymentsHandler.ashx.cs#L1088) for how to call `GetShippingAdresses()`.

**Comment by HoneyShyam** [comment]
Thank you Jason, I'll update you if need further help.
Regards
Shyam

**Comment by jziaja** [comment]
Sounds good. :)

**Comment by HoneyShyam** [comment]
Hi Jason,
I am trying to get the resp.selectedAddress.addresseeName , however each time getting null value.
Is there any settings like shipping address required we have in standard paypal so that when create a Payment Request that I can send and each time get the value for selectedAddress.
Regards
Shyam

**Comment by jziaja** [comment]
When you make the `GetShippingAddresses()` call, what information are you specifying in `requestEnvelope` property of the `GetShippingAddressesRequest` parameter?

**Comment by HoneyShyam** [comment]
I am using the same example you provided. and using PayKey, getting success response for the call, however in each there is null response for resp.selectedAddress.addresseeName.

**Comment by jziaja** [comment]
When you create the `GetShippingAddressesRequest` object, try the following:

````csharp
RequestEnvelope requestEnvelope = new RequestEnvelope("en_US");
requestEnvelope.detailLevel = DetailLevelCode.RETURNALL;
GetShippingAddressesRequest request = new GetShippingAddressesRequest(requestEnvelope, parameters["key"]);
````

**Comment by HoneyShyam** [comment]
Hi Jason,
It is not even giving the addresseeName. please find the complete method I am using, also the 
request: 
requestEnvelope.detailLevel=ReturnAll&requestEnvelope.errorLanguage=en_US&key=AP-23119815K9918782X&
Response: 
responseEnvelope.timestamp=2015-01-27T21%3A21%3A26.871-08%3A00&responseEnvelope.ack=Success&responseEnvelope.correlationId=6a242f2ded5d9&responseEnvelope.build=13414382
In the address no response.
For Payment I am using my PayPal account and there is Shipping Address.
Also Please let me know if we can set required shipping address in the Request Pay Methods. If possible how. 
![getshippingaddress](https://cloud.githubusercontent.com/assets/2680801/5933072/4fb24758-a6e0-11e4-9230-873f6bffdf8e.png)

Regards
Shyam

**Comment by jziaja** [comment]
Doing a lookup of that `payKey`, there doesn't seem to be a payment associated with it, which is needed in order to get any shipping information.  Can you try it again using a `payKey` that you know is associated with a payment?

**Comment by HoneyShyam** [comment]
The key I am using is with the actual transaction, However later I have get refunded it.
key=AP-23119815K9918782X

**Comment by HoneyShyam** [comment]
@jziaja Any idea how to achieve it.

**Comment by ppmtscory** [comment]
@HoneyShyam can you provide the transaction ID of the original transaction as I'm still not finding anything with that paykey.  Also, are you using the embedded flow for adaptive payments or the normal web flow?

**Comment by HoneyShyam** [comment]
@ppmtscory Please find the complete response on Notification
Receiver email and website name have been updated, rest of the response id original. Also put break to make it readable. We are using normal web flow.

&transaction[0].is_primary_receiver=true
&transaction[0].id_for_sender_txn=823015785J306733Y
&log_default_shipping_address_in_transaction=false
&transaction[0].receiver = sxxxxxxn@sxxxxxxxxr.com
&action_type=PAY
&ipn_notification_url=http://www.example.com/pay/IPNPayPalAdaptive.aspx
&transaction[1].paymentType=SERVICE
&transaction[0].amount=USD 0.10
&charset=windows-1252
&transaction_type=Adaptive Payment PAY
&transaction[1].id_for_sender_txn=5D530104L6567614X
&transaction[0].invoiceId=INV-EEB6D2203-S
&transaction[1].is_primary_receiver=false
&transaction[0].status=Completed
&notify_version=UNVERSIONED
&transaction[0].id=4WB90212J0067742W
&cancel_url=http://store.example.com/details/2218607-crafting-paper-crafting-day-of-the-dead-flower-single.html
&transaction[1].status_for_sender_txn=Completed
&transaction[1].receiver=sales@payloadz.com
&verify_sign=AQU0e5vuZCvSg-XJploSa.sGUDlpAfjqRmLWi02AblZbnQvEl3CJM2HB
&sender_email = shyamraghuvanshi@gmail.com
&fees_payer=PRIMARYRECEIVER
&transaction[0].status_for_sender_txn=Completed
&return_url=https://example.com/d1/
&transaction[0].paymentType=SERVICE
&memo=Buying Test Adaptive sales1(PLDZ-2001) at Price: USD0.1000
&transaction[1].amount=USD 0.02
&reverse_all_parallel_payments_on_error=true
&tracking_id=INV-EEB6D2203
&transaction[1].pending_reason=NONE
&pay_key=AP-28916903FP1674334
&transaction[1].id=5NN59372AH636272P
&transaction[0].pending_reason=NONE
&transaction[1].invoiceId=INV-EEB6D2203-M
&status=COMPLETED
&transaction[1].status=Completed
&payment_request_date=Tue Jan 27 04:25:05 PST 2015

**Comment by ppmtscory** [comment]
Thank you @HoneyShyam.  The issue is that you are not passing through a shipping address via SetPaymentOptions.  When doing the web flow of adaptive payments, the only way to get a shipping address is to send it through via [SetPaymentOptions](https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/) under the SenderOptions fields.

**Comment by HoneyShyam** [comment]
Thanks @ppmtscory.
I have set SetPaymentOptions senderOptions.requireShippingAddressSelection=true with and call the method 
requestEnvelope.errorLanguage=en_US&payKey=AP-28916903FP1674334&displayOptions.businessName=Shyam+Inc&senderOptions.requireShippingAddressSelection=true&
and Get the response : 
responseEnvelope.timestamp=2015-02-05T22%3A38%3A29.044-08%3A00&responseEnvelope.ack=Success&responseEnvelope.correlationId=85f3aa47c9df9&responseEnvelope.build=15089777

And could not anything with the AppKey
Now can you please guide me how can I call it when make final payment and then get the Address.
Regards
Shyam

**Comment by ppmtscory** [comment]
@HoneyShyam setting requireShippingAddressSelection=true is for the Embedded flow and allows the customer to select which address they'd like to use.  When using the web flow, you have to pass the address through using the shipping address fields under the sender options like below (you'll need to format for how you're sending):

"senderOptions.shippingAddress.addresseeName" => "Jane Jones",
"senderOptions.shippingAddress.street1" => "246 main st",
"senderOptions.shippingAddress.street2" => null,
"senderOptions.shippingAddress.city" => "Beverly Hills",
"senderOptions.shippingAddress.state" => "CA",
"senderOptions.shippingAddress.zip" => "90210",
"senderOptions.shippingAddress.country" => "US",

**Comment by HoneyShyam** [comment]
Thank you @ppmtscory , if I had these type of info then I can get it from my end, but I don't have. I am using  Embedded flow, actually I was not aware about it the difference between Embedded and  web flow.

**Comment by ppmtscory** [comment]
@HoneyShyam Ah, ok, I was curious why you'd need it from PayPal if you already had it to send through.  I assumed you just also wanted it attached to the transaction and able to call back to it later.  Either way, thanks for the clarification that you are using the Embedded flow.  When doing this with the Embedded flow, I'm also not able to get the shipping address returned so this seems to be a bug that we'll have to look in to.

**Comment by HoneyShyam** [comment]
@ppmtscory I said I don't have buyer's info. It was with us we don't not to get it from PayPal.
So If there is anyway to get Buyer Info using Adaptive Payments.
Regards
Shyam

**Comment by ppmtscory** [comment]
@HoneyShyam As I previously stated, if you are using the 'minibrowser' version of the Embedded flow, the GetShippingAddresses returns the address and name appropriately.  If you are using the 'lightbox' version, then I've already filed an issue internally as that particular version of the Embedded flow is not returning the name and address appropriately.  Please use the minibrowser version for the time being.

**Comment by HoneyShyam** [comment]
Thanks @ppmtscory,
Can you please share and suggest the sample code for minibrowser version.
Regards
Shyam

**Comment by ppmtscory** [comment]
@HoneyShyam Please review the section "Setting Up Web Pages to Invoke the Embedded Payment Flow Using a Minibrowser" on the [Adaptive Payments page](https://developer.paypal.com/webapps/developer/docs/classic/adaptive-payments/integration-guide/APIntro/) of the developer portal.  Essentially you do the same thing you are doing now for the lightbox but instead of specifying "light" for the expType, you'll specify "mini".

**Comment by HoneyShyam** [comment]
Thanks again @ppmtscory,
Can you please confirm following the Link https://www.payloadz.com/go/sip?id=180344&aff_id=3924
which flow is working here. I am not sure, what exactly it is.
Thanks again for your support to make it finally at the end of conclusion.

**Comment by ppmtscory** [comment]
@HoneyShyam that is the web flow; *not* the embedded flow.  There's no way for me to know their exact integration other than just that it's the web flow.

**Comment by HoneyShyam** [comment]
Thanks @ppmtscory, So I need to implement it in another way as you suggested.

**Comment by ppmtscory** [comment]
@HoneyShyam I just wanted to update you that this is working for the lightbox version as well as the minibrowser version.

**Comment by HoneyShyam** [comment]
Thanks for update.

On Fri, Feb 13, 2015 at 10:27 PM, Cory <notifications@github.com> wrote:

> @HoneyShyam <https://github.com/HoneyShyam> I just wanted to update you
> that this is working for the lightbox version as well as the minibrowser
> version.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/paypal/adaptivepayments-sdk-dotnet/issues/17#issuecomment-74286348>
> .
>



-- 
Warm Regards,
Shyam Raghuvanshi,
Phone +91 9872487838
