### ISSUE TITLE
ASP.NET Paypal Adaptive Payments

### ISSUE THREAD

**Issue by maximomass** [paypal/adaptivepayments-sdk-dotnet#18]
Dear Mr.Jason,

Regarding your request here is my code and issues I am facing. I am currently trying to input the code behind view in C#, the idea is to have a payment system that Buyer buys a product from my store I receive the money as the Primary recipient, then the second recipient receive their pay from me, the Primary Receiver.  This code is for chained payments but I am having great difficulty trying to get it to work as I don't understand much (x.com used to have all the information as Ive read on forums and viewed a snapshot of their website using web archive tools but cannot get detailed information). Here is the code from the behind view 
Code is from PlanetCam.aspx - on a Image Button - C#

````csharp
        Dictionary<string, string> paypalConfig = new Dictionary<string, string>();
        paypalConfig.Add("account1.apiUsername", "xxxxxxxxxxxxx_api1.gmail.com");
        paypalConfig.Add("account1.apiPassword", "xxxxxxxxxxxxxxx");
        paypalConfig.Add("account1.apiSignature", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        paypalConfig.Add("account1.applicationId", "APP-80W284485P519543T");
        paypalConfig.Add("IPNEndpoint", "https://www.paypal.com/cgi-bin/webscr");
        paypalConfig.Add("url", "https://www.paypal.com/webscr&cmd=_express-checkout&token=");
        paypalConfig.Add("endpoint", "https://api-3t.paypal.com/2.0/");
        paypalConfig.Add("mode", "sandbox");
        ReceiverList receiverList = new ReceiverList();
        receiverList.receiver = new List<Receiver>();
        Receiver secondaryReceiver = new Receiver((decimal?)2.00);
        secondaryReceiver.email = "xxxxxxxx@gmail.com";
        secondaryReceiver.primary = false;
        secondaryReceiver.paymentType = "GOODS";
        receiverList.receiver.Add(secondaryReceiver);
        Receiver primaryReceiver = new Receiver((decimal?)10.00);
        primaryReceiver.email = "xxxxxxxxxxx-facilitator@gmail.com ";
        primaryReceiver.primary = true;
        primaryReceiver.paymentType = "GOODS";
        primaryReceiver.invoiceId = "123456789";
        receiverList.receiver.Add(primaryReceiver);
        RequestEnvelope requestEnvelope = new RequestEnvelope("en_AU");
        string actionType = "Pay";
        string returnUrl = "https://devtools-paypal.com/guide/ap_chained_payment/dotnet?success=true";
        string cancelUrl = "https://devtools-paypal.com/guide/ap_chained_payment/dotnet?cancel=true";
        string currencyCode = "AUD";
        PayRequest payRequest = new PayRequest(requestEnvelope, actionType, cancelUrl, currencyCode, receiverList, returnUrl);

        payRequest.ipnNotificationUrl = "http://replaceIpnUrl.com";

        payRequest.feesPayer = "PRIMARYRECEIVER";
        payRequest.trackingId = "123456789";
        PayPal.AdaptivePayments.AdaptivePaymentsService service = new PayPal.AdaptivePayments.AdaptivePaymentsService(sdkConfig);
        PayResponse response = service.Pay(payRequest);

        string redirectUrl = null;

        if (!response.responseEnvelope.ack.ToString().Trim().ToUpper().Equals(AckCode.FAILURE.ToString()) && !response.responseEnvelope.ack.ToString().Trim().ToUpper().Equals(AckCode.FAILUREWITHWARNING.ToString()))
        {
            redirectUrl = "https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=" + response.payKey;
        }
````

Please note I got this from the PayPal website although I have made a few little changes, here is the link to this : https://devtools-paypal.com/guide/ap_chained_payment/dotnet?interactive=ON&env=sandbox
I don't know what goes in the Web.config files, or other locations I'm trying my best to see what I can do, the only error I have had so far is an 500 internal server error.

Thanks for responding back to me and I appreciate your help!

Max

**Comment by mjmasn** [comment]
Hi Max,

I don't have any relation to PayPal but noticed some possible issues with the code you posted:
* The sandbox only supports the USD currency (last time I checked, this may have changed). 
* Your endpoint looks incorrect for adaptive payments - should be https://svcs.sandbox.paypal.com/AdaptivePayments/ (although I'm not sure you need to set an endpoint)

I've posted an example below that's loosely based on code we've used in the past with .NET. I haven't tested the code but hopefully it will point you in the right direction...

```csharp
ReceiverList receiverList = new ReceiverList();
receiverList.receiver = new List<Receiver>();
PayRequest request = new PayRequest();
RequestEnvelope requestEnvelope = new RequestEnvelope("en_US");
request.requestEnvelope = requestEnvelope;

Dictionary<string, string> configurationMap = new Dictionary<string, string>();

configurationMap.Add("account1.apiUsername", "...");
configurationMap.Add("account1.apiPassword", "...");
configurationMap.Add("account1.apiSignature", "...");
configurationMap.Add("account1.applicationId", "APP-80W284485P519543T");

configurationMap.Add("mode", "sandbox");

// Note that if the total sale is $10, primary receiver amount will be $10
// The other receiver amounts are then deducted from this, so receiver 1 gets
// $8 and receiver2 gets $2, $8 + $2 = $10

Receiver receiver1 = new Receiver();
receiver1.amount = 10.00;
receiver1.email = "...";
receiver1.primary = true;

receiverList.receiver.Add(receiver1);

Receiver receiver2 = new Receiver();
receiver2.amount = 2.00;
receiver2.email = "...";
receiver2.primary = false;

receiverList.receiver.Add(receiver2);


request.receiverList = receiverList;

request.actionType = "PAY";

// Change this is primary receiver is paying all the fees
request.feesPayer = "EACHRECEIVER";

request.cancelUrl = "...";
request.returnUrl = "...";
request.ipnNotificationUrl = "...";

// Sandbox account is USD only...
request.currencyCode = 'USD';

request.requestEnvelope = requestEnvelope;

AdaptivePaymentsService service = new AdaptivePaymentsService(configurationMap);
PayResponse response = service.Pay(request);


if (!response.responseEnvelope.ack.ToString().Trim().ToUpper().Equals(AckCode.FAILURE.ToString())
    && !response.responseEnvelope.ack.ToString().Trim().ToUpper().Equals(AckCode.FAILUREWITHWARNING.ToString()))
{
    // Do something with the response
    // e.g. return response.payKey;
}
else
{
    // Error occurred
    // ... handle the error
}
```

Hope this helps,

Cheers,
Mike

**Comment by maximomass** [comment]
@mjmasn Many thanks Kind Sir, as well to Mr Jason! all credits to you all! here is the code that works for me, and so far no issues! the only thing I have to workout is trying to find out how to add TAX(GST) to the payments when the buyer pays for it which is 10% for my country Aus. Here is the code : 

 protected void ImageButton1_Click1(object sender, ImageClickEventArgs e)
    {
ReceiverList receiverList = new ReceiverList();
receiverList.receiver = new List<Receiver>();
PayRequest request = new PayRequest();
RequestEnvelope requestEnvelope = new RequestEnvelope("en_US");
request.requestEnvelope = requestEnvelope;

Dictionary<string, string> configurationMap = new Dictionary<string, string>();

configurationMap.Add("account1.apiUsername", "xxxxxxxxxx_api1.gmail.com");
configurationMap.Add("account1.apiPassword", "xxxxxxxxxxxxxxxx");
configurationMap.Add("account1.apiSignature", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
configurationMap.Add("account1.applicationId", "APP-80W284485P519543T");

configurationMap.Add("mode", "sandbox");

// Note that if the total sale is $10, primary receiver amount will be $10
// The other receiver amounts are then deducted from this, so receiver 1 gets
// $8 and receiver2 gets $2, $8 + $2 = $10

Receiver receiver1 = new Receiver();
receiver1.amount = ((decimal)8.99);
receiver1.email = "xxxxxxxxx@gmail.com";
receiver1.primary = true;

receiverList.receiver.Add(receiver1);

Receiver receiver2 = new Receiver();
receiver2.amount = ((decimal)1.70);
receiver2.email = "xxxxxxx@gmail.com";
receiver2.primary = false;

receiverList.receiver.Add(receiver2);


request.receiverList = receiverList;

request.actionType = "PAY";

// Change this is primary receiver is paying all the fees
request.feesPayer = "EACHRECEIVER";

request.cancelUrl = "Your Cancel URL";
request.returnUrl = "RETURN URL AFTER SUCCESSFUL PAYMENT BY BUYER";
//request.ipnNotificationUrl = "...";

// Sandbox account is USD only..., ADDED THIS, works with AUD too Ive tested it.
request.currencyCode = "AUD";

request.requestEnvelope = requestEnvelope;

AdaptivePaymentsService service = new AdaptivePaymentsService(configurationMap);
PayResponse response = service.Pay(request);

String redirectURL = "https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=";
if (!response.responseEnvelope.ack.ToString().Trim().ToUpper().Equals(AckCode.FAILURE.ToString())
    && !response.responseEnvelope.ack.ToString().Trim().ToUpper().Equals(AckCode.FAILUREWITHWARNING.ToString()))
{
    // Do something with the response
    // e.g. return response.payKey;

    Response.Redirect(redirectURL + response.payKey);
}
else
{
    // Error occurred
    // ... handle the error
    Response.Redirect(redirectURL = "Your URL");
}

Many thanks again!, just need to figure out how to add TAX if I can.

**Comment by jziaja** [comment]
Glad you got the code working, @maximomass, and a huge thanks to @mjmasn for providing the sample!

Regarding your question, @maximomass about adding the tax, it looks like the only option available is by setting the `totalTax` in the invoice data for the payment by calling [`SetPaymentOptions()`](https://developer.paypal.com/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/).

**Comment by yashsharmanice** [comment]
Hello Guys,


I Used Same Code for Delayed Chained Payment as i Used ActionTYpe as Pay_PRIMARY. but it is giving me error while generating Pay Reqest.
Excaption is As Follows:-

                    PayPal.Exception.ConnectionException: Invalid HTTP response The underlying connection was closed: An unexpected error occurred on a receive.
                    at PayPal.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
                    at PayPal.APIService.MakeRequestUsing(IAPICallPreHandler apiCallHandler)
                    at PayPal.BasePayPalService.Call(IAPICallPreHandler apiCallHandler)
                    at PayPal.AdaptivePayments.AdaptivePaymentsService.Pay(PayRequest payRequest, String apiUserName)
                    at PayPal.AdaptivePayments.AdaptivePaymentsService.Pay(PayRequest payRequest)
                    at Payme101.Controllers.HomeController.Order_Pay(Order_Pay single) in d:\Completed\Payme10\Payme101\Payme101\Controllers\HomeController.cs:line 2404


Can Anybody tell me Why this is Happening and How can i Resolve this??

**Comment by pp-randy** [comment]
@yashsharmanice Are you able to provide the request string being sent to PayPal?

**Comment by yashsharmanice** [comment]
@pp-randy Not Actually, This is Giving me Exception when we Create object of AdaptivePaymentsService. Though code is working perfectly when i uploaded it on another web Server.
 Here is the Line when I am getting Exception:-
AdaptivePaymentsService service = new AdaptivePaymentsService(configurationMap);

**Comment by pp-randy** [comment]
@yashsharmanice your code runs for me. 

When researching the error this could be a timeout at a server or networking device.  The other web server is it on a separate network?

**Comment by yashsharmanice** [comment]
@pp-randy  Yes Sir. It is on Seperate Network. Other Paypal Codes are also working on That Server. Only this Code is Generating that Exception.
