### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mjmasn** [paypal/adaptivepayments-sdk-dotnet#19]
@pp-randy I know this is the wrong place but I've exhausted other methods of trying to get this issue sorted... 

Would you by any chance have contact details for someone who can approve the funding constraints permission for our two Adaptive Payments apps (One UK based, one SG based). 

I have sent multiple messages on the legacy apps dashboard, which have gone unanswered for 30+ days, to `pp_par_amy` and `pp_par_daragh`, whoever they are. I have also contacted general PayPal developer support a couple times over the past year but I don't think anyone there knows anything about these legacy APIs. Last I was told (in December 2015) they would chase up the messages on the dashboard, but heard nothing since. 

Really frustrated and disappointed that PayPal is happy to take a hefty cut of our sales but refuses to communicate effectively with their customers. I appreciate these APIs are 'legacy' but that's no excuse for the service I've received from customer support. Hopefully you can put me in touch with someone who knows what they are doing.

Cheers,

Michael

**Comment by pp-randy** [comment]
@mjmasn Can you file an MTS ticket here https://www.paypal-techsupport.com/app/ask/

Provide your email address in the ticket then please provide the ticket number back to this thread.

**Comment by mjmasn** [comment]
@pp-randy thanks, the ticket number is #160112-000157
