### ISSUE TITLE
Packages are missing on nuget command even though they are listed on nuget website.

### ISSUE THREAD

**Issue by ronin1** [paypal/adaptivepayments-sdk-dotnet#20]
This is what I get when I do a package update in nuget console 
```
PM> Update-Package PayPalAdaptivePaymentsSDK
No updates available for 'PayPalAdaptivePaymentsSDK' in project 'Panjo.Business'.
No updates available for 'PayPalAdaptivePaymentsSDK' in project 'Panjo'.
```

Doing a nuget install-package gives the same results.

**Comment by pp-randy** [comment]
Do you see PayPalAdaptivePaymentsSDK and PayPalCoreSDK in your References?  I tested in a new project and was able to get these with install-package.

**Comment by pp-randy** [comment]
Closing the issue, please let us know if you are still getting an error.
